// Ported from build.py in the lead-timeline prototype. These rules are tuned
// against real Salesforce data -- change them there and here together, or not
// at all.

export type EventKind =
  | "stage_change" | "status_change" | "meeting_booked" | "meeting_declined"
  | "meeting_invite" | "call" | "call_in" | "sms" | "email_in" | "email_out"
  | "system_email" | "other";

const STAGE_CHANGE_RE = /^Field Change Stage:\s*(.+)$/;
const LEAD_STATUS_RE = /^Field Change Prospecting Lead Status:\s*(.+)$/;
export const SEQUENCE_RE = /\[([^\]]+)\]/;
// Activities logged by the Outreach connector carry their own direction tags.
const OUTREACH_RE = /^\[Outreach\]\s*\[(\w+)\]\s*\[(In|Out)\]\s*(.*)$/;

// Mail generated by a machine rather than by the prospect. Bounces, delivery
// notices, autoresponders and list plumbing all arrive as inbound email and
// would otherwise read as the prospect getting in touch.
const SYSTEM_EMAIL_RE =
  /out of office|automatic reply|auto-?reply|autoreply|undeliverable|delivery (status|has failed|failure)|mail delivery|postmaster|returned mail|bounced|unsubscribe|do.?not.?reply|no longer with (the )?compan|has left the compan/i;

export type RawTask = {
  id: string;
  subject: string | null;
  tasksubtype: string | null;
  calltype: string | null;
};

/** Map a Task onto one of the timeline's mark types. */
export function classify(task: RawTask): [EventKind, string] {
  const subject = (task.subject || "").trim();

  const stage = STAGE_CHANGE_RE.exec(subject);
  if (stage) return ["stage_change", stage[1].trim()];
  const status = LEAD_STATUS_RE.exec(subject);
  if (status) return ["status_change", status[1].trim()];

  if (task.tasksubtype === "Call") {
    // A dialer disposition of "Booked Meeting" is the outcome, not the call.
    if (subject.includes("Booked Meeting")) return ["meeting_booked", subject];
    // CallType is the reliable direction flag; the subject text is not.
    if (task.calltype === "Inbound") return ["call_in", subject];
    return ["call", subject];
  }
  if (subject.startsWith("Dialpad messages")) return ["sms", subject];

  // Calendar traffic -- the clearest signal that a meeting was actually set.
  // An "Accepted:" reply comes from the prospect and is the booking itself;
  // an invitation is still only the rep asking.
  const outreach = OUTREACH_RE.exec(subject);
  const body = outreach ? outreach[3].trim() : subject;

  if (body.startsWith("Accepted:")) return ["meeting_booked", body];
  if (body.startsWith("Declined:")) return ["meeting_declined", body];
  if (/^(Updated )?[Ii]nvitation:/.test(body) || body.startsWith("Reminder:")) {
    return ["meeting_invite", body];
  }

  if (outreach) {
    if (outreach[2] === "In" && SYSTEM_EMAIL_RE.test(body)) return ["system_email", body];
    return [outreach[2] === "In" ? "email_in" : "email_out", body];
  }

  if (subject.startsWith("Replied")) return ["email_in", subject];
  if (subject.startsWith("Sent")) return ["email_out", subject];
  if (subject.startsWith("Received: Read:")) return ["system_email", subject];
  if (subject.startsWith("Received: Not read:")) return ["system_email", subject];
  if (subject.startsWith("Received:")) {
    return SYSTEM_EMAIL_RE.test(subject) ? ["system_email", subject] : ["email_in", subject];
  }

  return ["other", subject];
}

// The lane is coloured by the stage in force at that moment, so the horizontal
// line carries the lead's temperature over time. Checked in order: a dead end
// wins over everything, and "Closed Won" must be caught before Hot/Warm.
const STAGE_BUCKETS: [string, RegExp][] = [
  ["dead", /DQ |No Quote|Closed Lost/i],
  ["generated", /Closed Won/i],
  ["ltfu", /LT Follow Up/i],
  ["cold", /Cold/i],
  ["warm", /Warm/i],
  ["hot", /Hot/i],
  ["generated", /Lead Generated/i],
];

export function stageBucket(stage: string | null): string {
  for (const [name, pattern] of STAGE_BUCKETS) {
    if (pattern.test(stage || "")) return name;
  }
  return "other";
}

// Marks the rep made: the touches follow-up speed is measured on.
export const REP_TOUCH = new Set<EventKind>(["email_out", "call", "sms", "meeting_invite"]);
// Marks the prospect made: a live signal the rep is expected to answer.
export const PROSPECT_SIGNAL = new Set<EventKind>(["email_in", "call_in", "meeting_booked"]);
// Never drawn and never counted -- machine mail, not a person.
export const DROPPED = new Set<EventKind>(["system_email"]);

export const COLD_AFTER_DAYS = 14;

export type Outcome = { key: string; label: string; status: string };

// status drives the chip colour and is one of the four reserved status roles,
// never a categorical hue.
export function outcomeFor(
  stage: string,
  lastEventDays: number | null,
  referredBy: string | null
): Outcome {
  const o = (key: string, label: string, status: string) => ({ key, label, status });

  if (stage.startsWith("Closed: Closed Won")) return o("won", "Closed won", "good");
  if (stage.startsWith("Closed: DQ Contact")) return o("dq_contact", "DQ — contact", "serious");
  if (stage.startsWith("Closed: DQ Company")) return o("dq_company", "DQ — company", "serious");
  if (stage.startsWith("Closed: No Quote")) return o("no_quote", "No quote", "critical");
  if (stage.startsWith("Closed: Closed Lost")) return o("lost", "Closed lost", "critical");

  if (stage === "Lead Generated: Scheduled") return o("meeting", "Meeting scheduled", "good");
  if (stage === "Lead Generated") return o("lead_generated", "Lead delivered", "good");
  if (stage === "Pipeline Hot: Appointment set") return o("meeting", "Appointment set", "good");

  if (stage.includes("Referral") || stage === "Prospecting: Referred" || referredBy) {
    return o("referred", "Referred on", "neutral");
  }

  const cold = lastEventDays !== null && lastEventDays >= COLD_AFTER_DAYS;
  if (stage === "Pipeline: LT Follow Up") return o("nurture", "Long-term follow up", "warning");
  if (stage.startsWith("Pipeline Hot") || stage === "Pipeline: Hot") {
    return cold ? o("cold", "Hot — gone quiet", "warning") : o("hot", "Hot", "good");
  }
  if (stage === "Pipeline: Warm") {
    return cold ? o("cold", "Warm — gone quiet", "warning") : o("warm", "Warm", "neutral");
  }
  if (stage.startsWith("Prospecting")) {
    return cold
      ? o("cold", "Prospecting — no traction", "warning")
      : o("prospecting", "Prospecting", "neutral");
  }

  return o("other", stage, "neutral");
}

/** Loose key for comparing company names across fields. */
export function norm(text: string | null): string {
  return (text || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}
