/*
 * Every page the app has, written out for the usage report to read.
 *
 * Generated rather than hand-kept, and generated on every build rather than
 * when somebody remembers: a list of pages that quietly stops matching the
 * pages is worse than no list, because the ones missing from it are invisible
 * rather than obviously absent.
 *
 * Runs as `prebuild`, so `npm run build` cannot produce a stale one.
 */

import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const appDir = join(here, "..", "app");

/** Route groups like (dashboard) organise files; they are not part of a URL. */
const isGroup = (name) => name.startsWith("(") && name.endsWith(")");

/** @param {string} dir @param {string} route */
function walk(dir, route, out) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      if (/^page\.(tsx|ts|jsx|js)$/.test(entry.name)) out.add(route || "/");
      continue;
    }
    // Private folders and colocated internals are not routes.
    if (entry.name.startsWith("_") || entry.name === "api") continue;
    walk(
      join(dir, entry.name),
      isGroup(entry.name) ? route : `${route}/${entry.name}`,
      out
    );
  }
}

const routes = new Set();
walk(appDir, "", routes);

const sorted = [...routes].sort();

mkdirSync(join(here, "..", "lib"), { recursive: true });
writeFileSync(
  join(here, "..", "lib", "routes.generated.ts"),
  `// Generated by scripts/routes.mjs on every build. Do not edit.\n` +
    `export const ROUTES: readonly string[] = ${JSON.stringify(sorted, null, 2)} as const;\n`
);

console.log(`routes.generated.ts — ${sorted.length} pages`);
